### ISSUE TITLE
Helo me please

### ISSUE THREAD

**Issue by ZoltXs** [arzzen/philips-tv#1]
Hello, you could help me. I'm new with this and my goal is to install Homebridge Philips from 2018. I have followed this tutorial and when I run 192.168.0.182 "& &./tv.sh <12> does nothing, I do wrong???

**Comment by arzzen** [comment]
Hi @ZoltXs you must export variable like `export _TV_IP="192.168.0.182"` after then you can run `./tv.sh` 
eg: one line command `export _TV_IP="192.168.0.182" && ./tv.sh standby`
