### ISSUE TITLE
How to re-pair?

### ISSUE THREAD

**Issue by pjensen1977** [arzzen/philips-tv#5]
Hi,

i entered the wrong pin number, then i have not been able to redo the pair. I removed the .credentials.tv file but he did not ask for a pin again.

How can i get this fixed?

**Comment by lucasvdh** [comment]
Removing the `.credentials.tv` should be sufficient. I think it only starts the pairing process when you try to execute a command.

Try running `tv.sh` and then execute the command `5` for example. It should start the pairing process when it sees there's no `.credentials.tv` file.
